http:
  routers:
    portainer:
      rule: "Host(`portainer.techomelab.com`)"
      entryPoints:
        - websecure
      service: portainer
  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://192.168.86.22:9443"
        serversTransport: portainerTransport
  serversTransports:
    portainerTransport:
      insecureSkipVerify: true
