http:
  routers:
    uptime:
      rule: "Host(`omada.techomelab.com`)"
      entryPoints:
        - websecure
      service: uptime
  services:
    uptime:
      loadBalancer:
        servers:
          - url: "http://192.168.86.10:8043"
